# codemagic.yaml
workflows:
  simple-flutter-app:
    name: Build Android APK
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android release
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com  # ← غيّر هذا إلى بريدك
